import React, { Component } from "react";
interface IProps {}
import { ConfigProvider, Spin, InputNumber, List, Avatar, Icon } from "antd";
import "./styles.css";

const foods = {
  beverages: {
    id: "beverages",
    name: "Напитки",
    items: [
      {
        id: 1,
        name: "Святой источник, 0.5, негаз",
        total: 7,
        exp: "20190707",
        price: 50,
        compos: `Тип воды
          питьевая
          Вид воды
          природная
          Артезианская
          да
          Материал упаковки
          пластик
          Стандарты производства
          ГОСТ Р 52109-2003
          Состав
          кальций <80, магний <20, калий <20, гидрокарбонаты <250, хлориды <150, сульфаты <50`,
        img: "./assets/drinks/saintSpring.jpg"
      },
      {
        id: 2,
        name: "Шишкин лес, 0.4, негаз",
        img: "./assets/drinks/shiskinLes.jpg",
        total: 7,
        price: 50
      },
      {
        id: 3,
        name: "Сенежская, 0.5, негаз",
        img: "./assets/drinks/senejskaya.jpg",
        total: 7,
        price: 55
      },
      {
        id: 4,
        name: "Липецкий бювет, 0.5, негаз",
        img: "",
        total: 7,
        price: 55
      }
    ]
  },
  sandwiches: {
    id: "sandwiches",
    name: "Сэндвичи",
    items: []
  }
};

export class VendingMachine extends Component<IProps> {
  state = {
    isMenuVisible: true,
    isOrderPayVisible: false,
    isMenuItemsVisible: false,
    isThankForShoppingVisible: false,
    isTrayTextVisible: false,
    selectedMenuItem: {},
    selectedMenuItemId: "",
    orderItems: {}
  };

  onClickMenuItem = id => () => {
    console.log(id, foods[id].items);
    this.setState({
      selectedMenuItem: foods[id].items,
      selectedMenuItemId: id,
      isMenuVisible: false,
      isMenuItemsVisible: true,
      isOrderPayVisible: false,
      isThankForShoppingVisible: false,
      isTrayTextVisible: false
    });
  };

  onClickBackMenu = () => {
    this.setState({
      isMenuVisible: true,
      isOrderPayVisible: false,
      isMenuItemsVisible: false,
      isThankForShoppingVisible: false,
      isTrayTextVisible: false
    });
  };

  onAddFoodToCart = food => () => {
    this.setState((state, nextProps) => {
      const id = this.getOrderItemId(food.id);
      const num = state.orderItems[id] ? state.orderItems[id].num + 1 : 1;
      const sum = num * food.price;
      return {
        orderItems: {
          ...state.orderItems,
          [id]: {
            ...food,
            num,
            sum
          }
        }
      };
    });
  };

  onDeleteFood = id => () => {
    this.setState(state => {
      let newOrderItems = { ...state.orderItems };
      delete newOrderItems[this.getOrderItemId(id)];
      return {
        orderItems: newOrderItems
      };
    });
  };

  onChangeItemNum = food => number => {
    this.setState((state, nextProps) => {
      const id = this.getOrderItemId(food.id);
      const num = number;
      const sum = num * food.price;
      return {
        orderItems: {
          ...this.state.orderItems,
          [id]: {
            ...food,
            num,
            sum
          }
        }
      };
    });
  };

  onClickPay = () => {
    this.setState({
      isOrderPayVisible: true,
      isMenuVisible: false,
      isMenuItemsVisible: false,
      isThankForShoppingVisible: false,
      isTrayTextVisible: false
    });
  };

  onPay = () => {
    this.setState({
      isOrderPayVisible: false,
      isMenuVisible: false,
      isMenuItemsVisible: false,
      isThankForShoppingVisible: true
    });

    setTimeout(() => {
      this.setState({
        isTrayTextVisible: true,
        isMenuVisible: true,
        isThankForShoppingVisible: false
      });
    }, 5000);
  };

  getOrderItemId = id => `${this.state.selectedMenuItemId}_${id}`;

  getOrderSum = () => {
    const { orderItems } = this.state;
    return Object.values(orderItems).reduce((sum, next) => sum + next.sum, 0);
  };

  componentDidMount() {}

  render() {
    const {
      selectedMenuItem,
      isMenuVisible,
      isMenuItemsVisible,
      isThankForShoppingVisible,
      isTrayTextVisible,
      orderItems,
      isOrderPayVisible
    } = this.state;

    const customizeRenderEmpty = () => (
      <div>
        <Icon type="shopping-cart" style={{ fontSize: 80 }} />
      </div>
    );
    const orderItemsVals = Object.values(orderItems);
    const MyIcon = Icon.createFromIconfontCN({
      scriptUrl: "//at.alicdn.com/t/font_1195976_c20y2ritutp.js" // generated by iconfont.cn
    });
    return (
      <div className="machine">
        <div className="inner">
          {isMenuVisible && (
            <div className="menu">
              <List
                dataSource={Object.values(foods)}
                renderItem={food => (
                  <List.Item onClick={this.onClickMenuItem(food.id)}>
                    {food.name}
                  </List.Item>
                )}
              />
            </div>
          )}
          {isMenuItemsVisible && (
            <div>
              <span className="backToMenu" onClick={this.onClickBackMenu}>
                Меню
              </span>
              <div className="menuItem">
                <List
                  dataSource={selectedMenuItem}
                  renderItem={item => (
                    <List.Item
                      actions={[
                        <Icon
                          type="shopping-cart"
                          className="font-24"
                          onClick={this.onAddFoodToCart(item)}
                        />
                      ]}
                    >
                      <List.Item.Meta
                        avatar={<Avatar src={item.img} />}
                        title={item.name}
                        description={false && item.compos}
                      />
                    </List.Item>
                  )}
                />
              </div>
              <div className="order-sum display-flex">
                <MyIcon className="orderIcon" type="icon-receipt" />
                <span className="flex-g-one font-24 font-800 margin-l-4">
                  {this.getOrderSum()}р
                </span>
                {this.getOrderSum() > 0 && this.state.orderItems && (
                  <button onClick={this.onClickPay}>Оплатить</button>
                )}
              </div>
              <div className="order">
                <ConfigProvider renderEmpty={customizeRenderEmpty}>
                  <List
                    dataSource={orderItemsVals}
                    renderItem={item => (
                      <List.Item>
                        <List.Item.Meta
                          avatar={<Avatar src={item.img} />}
                          title={item.name}
                          description={
                            <div style={{ display: "flex" }}>
                              <InputNumber
                                size="small"
                                min={1}
                                max={item.total}
                                value={item.num}
                                onChange={this.onChangeItemNum(item)}
                              />
                              <span className="itemSum">{item.sum}р</span>
                              <Icon
                                type="close-circle"
                                onClick={this.onDeleteFood(item.id)}
                              />
                            </div>
                          }
                        />
                      </List.Item>
                    )}
                  />
                </ConfigProvider>
              </div>
            </div>
          )}
          {isOrderPayVisible && (
            <div className="flex-center">
              <MyIcon
                className="payIcon"
                type="icon-nfc"
                onClick={this.onPay}
              />
              <span className="margin-l-4">
                Для оплаты, приложите банковскую карту к экрану
              </span>
            </div>
          )}
          {isThankForShoppingVisible && (
            <div className="ta-center">
              Спасибо за покупку! <br />
              Ваш заказ готовится к выдаче
              <div>
                <Spin />
              </div>
            </div>
          )}
        </div>

        {/*        <div className="glass" /> */}
        <div className="tray-inner flex-center">
          <span className={`${isTrayTextVisible && "tray-text"}`}>
            Заберите заказ
          </span>
        </div>
      </div>
    );
  }
}
