import React, { Component } from "react";
interface IProps {}
import { Spin, InputNumber, List, Avatar, Icon } from "antd";
import "./styles.css";

const foods = {
  beverages: {
    id: "beverages",
    name: "Напитки",
    items: [
      {
        id: 1,
        name: "Святой источник, 0.5, негаз",
        total: 7,
        exp: "20190707",
        price: 50,
        compos: `Тип воды
          питьевая
          Вид воды
          природная
          Артезианская
          да
          Материал упаковки
          пластик
          Стандарты производства
          ГОСТ Р 52109-2003
          Состав
          кальций <80, магний <20, калий <20, гидрокарбонаты <250, хлориды <150, сульфаты <50`,
        img: ""
      },
      { id: 2, name: "Шишкин лес, 0.4, негаз", img: "", total: 7, price: 50 },
      { id: 3, name: "Сенежская, 0.5, негаз" }
    ]
  },
  sandwiches: {
    id: "sandwiches",
    name: "Сэндвичи",
    items: []
  }
};

export class VendingMachine extends Component<IProps> {
  state = {
    isMenuVisible: true,
    isOrderPayVisible: false,
    isMenuItemsVisible: false,
    isThankForShoppingVisible: false,
    isTrayTextVisible: false,
    selectedMenuItem: {},
    selectedMenuItemId: "",
    orderItems: {}
  };

  onClickMenuItem = id => () => {
    console.log(id, foods[id].items);
    this.setState({
      selectedMenuItem: foods[id].items,
      selectedMenuItemId: id,
      isMenuVisible: false,
      isMenuItemsVisible: true,
      isOrderPayVisible: false,
      isThankForShoppingVisible: false,
      isTrayTextVisible: false
    });
  };

  onClickBackMenu = () => {
    this.setState({
      isMenuVisible: true,
      isOrderPayVisible: false,
      isMenuItemsVisible: false,
      isThankForShoppingVisible: false,
      isTrayTextVisible: false
    });
  };

  onAddFoodToCart = food => () => {
    this.setState((prevState, nextProps) => {
      const id = `${prevState.selectedMenuItemId}_${food.id}`;
      const num = prevState.orderItems[id]
        ? prevState.orderItems[id].num + 1
        : 1;
      const sum = num * food.price;
      console.log(prevState);
      return {
        orderItems: {
          ...prevState.orderItems,
          [id]: {
            ...food,
            num,
            sum
          }
        }
      };
    });
  };

  onClickPay = () => {
    console.log("clickPay");
    this.setState({
      isOrderPayVisible: true,
      isMenuVisible: false,
      isMenuItemsVisible: false,
      isThankForShoppingVisible: false,
      isTrayTextVisible: false
    });
  };

  onPay = () => {
    this.setState({
      isOrderPayVisible: false,
      isMenuVisible: false,
      isMenuItemsVisible: false,
      isThankForShoppingVisible: true
    });

    setTimeout(() => {
      this.setState({
        isTrayTextVisible: true,
        isMenuVisible: true,
        isThankForShoppingVisible: false
      });
    }, 5000);
  };

  getOrderSum = () => {
    const { orderItems } = this.state;
    return Object.values(orderItems).reduce((sum, next) => sum + next.sum, 0);
  };

  componentDidMount() {}

  render() {
    const {
      selectedMenuItem,
      isMenuVisible,
      isMenuItemsVisible,
      isThankForShoppingVisible,
      isTrayTextVisible,
      orderItems,
      isOrderPayVisible
    } = this.state;
    const orderItemsVals = Object.values(orderItems);
    const MyIcon = Icon.createFromIconfontCN({
      scriptUrl: "//at.alicdn.com/t/font_1195976_c20y2ritutp.js" // generated by iconfont.cn
    });
    return (
      <div className="machine">
        <div className="inner flex-center">
          {isMenuVisible && (
            <div className="menu">
              <List
                dataSource={Object.values(foods)}
                renderItem={food => (
                  <List.Item onClick={this.onClickMenuItem(food.id)}>
                    {food.name}
                  </List.Item>
                )}
              />
            </div>
          )}
          {isMenuItemsVisible && (
            <div>
              <span className="backToMenu" onClick={this.onClickBackMenu}>
                Меню
              </span>
              <div className="menuItem">
                <List
                  dataSource={selectedMenuItem}
                  renderItem={item => (
                    <List.Item
                      actions={[
                        <Icon
                          type="shopping-cart"
                          onClick={this.onAddFoodToCart(item)}
                        />
                      ]}
                    >
                      <List.Item.Meta
                        avatar={<Avatar src="{item.img}" />}
                        title={item.name}
                        description={false && item.compos}
                      />
                    </List.Item>
                  )}
                />
              </div>
              <div className="order">
                <div className="ta-center">
                  <MyIcon className="orderIcon" type="icon-receipt" />
                  <span>{this.getOrderSum()}р</span>
                  <button className="margin-l-4" onClick={this.onClickPay}>
                    Оплатить
                  </button>
                </div>
                <List
                  dataSource={orderItemsVals}
                  renderItem={item => (
                    <List.Item
                      actions={[
                        <InputNumber
                          size="small"
                          min={1}
                          max={item.total}
                          value={item.num}
                        />,
                        <span>{item.sum}р</span>,
                        <Icon type="close-circle" />
                      ]}
                    >
                      <List.Item.Meta
                        avatar={<Avatar src="{item.img}" />}
                        title={item.name}
                        description={false && item.compos}
                      />
                    </List.Item>
                  )}
                />
              </div>
            </div>
          )}
          {isOrderPayVisible && (
            <div className="flex-center">
              <MyIcon
                className="payIcon"
                type="icon-nfc"
                onClick={this.onPay}
              />
              <span className="margin-l-4">
                Для оплаты, приложите банковскую карту к экрану
              </span>
            </div>
          )}
          {isThankForShoppingVisible && (
            <div className="ta-center">
              Спасибо за покупку! <br />
              Ваш заказ готовится к выдаче
              <div>
                <Spin />
              </div>
            </div>
          )}
        </div>

        {/*        <div className="glass" /> */}
        <div className="tray-inner flex-center">
          <span className={`${isTrayTextVisible && "tray-text"}`}>
            Заберите заказ
          </span>
        </div>
      </div>
    );
  }
}
