export const SET_NAVIGATION_HEADERS = "SET_NAVIGATION_HEADERS";
export const SET_NAVIGATION_DATA = "SET_NAVIGATION_DATA";
export const NAVIGATION_PER_PAGE = 20;
export const PROJECTS_LOADED = "PROJECTS_LOADED";
